
PGMS = principleValue hoursMinSec convertInvprojAsciiToBinary selectAndAppend selectAndSort selectAndSortBinary selectAndWrite selectSubAerial

all		: $(PGMS) 
		mv $(PGMS) ../bin

clean		:
		rm -f hoursMinSec principleValue  


